# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@3.0.0
  aws-s3: circleci/aws-s3@1.0.3

executors:
  node-executor:
    docker:
      - image: circleci/node:8.12.0
    working_directory: ~/project

jobs:
  install:
    executor: node-executor
    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - persist_to_workspace:
          root: /home/circleci
          paths: project

  lint_test_coverage:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Run Linter
          command: yarn run lint

      # - run:
      #     name: Run Tests
      #     command: yarn run test

      - run:
          name: Report to CodeCov
          command: npx codecov@3

      - persist_to_workspace:
          root: /home/circleci
          paths: project

  build_client:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/
      
      - run:
          name: Build Client
          command: yarn run build

      - persist_to_workspace:
          root: /home/circleci
          paths: project/client/build

  deploy_client:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/
      
      - aws-s3/sync:
          from: ~/project/client/build
          to: 's3://dx-portal'

workflows:
  build_test_deploy:
    jobs:
      - install
      - lint_test_coverage:
          requires:
            - install
      - build_client:
          requires:
            - lint_test_coverage
      - approve_deploy_client:
          type: approval
          requires:
            - build_client
      - deploy_client:
          requires:
            - approve_deploy_client
      - aws-ecr/build_and_push_image:
          repo: 'dx'
          tag: '${CIRCLE_BUILD_NUM}'
          requires:
            - lint_test_coverage
          filters:
            branches:
              only:
                - master
